- name: Compile sketch
        run: |
          mkdir -p ./CYD_FlipperUI
          cp $GITHUB_WORKSPACE/CYD_FlipperUI.ino ./CYD_FlipperUI/CYD_FlipperUI.ino
          mkdir -p ./build
          $HOME/bin/arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --output-dir ./build \
            ./CYD_FlipperUI
